### ISSUE TITLE
Broadcom BCM943224HMS not working on Monterey 12.3.1

### ISSUE THREAD

**Issue by avidal40** [chris1111/HP-ProbookEliteBook-Package-Creator-Clover#2]
Good afternoon,

In my HP EliteBook 2570P I had an Atheros AR9280 working well in Big Sur, but in Monterey is out totally, so I tried to buy this BCM943224HMS that I read here is compatible with Monterey, but after doing a lot of tries, I only could get it working through Big Sur, but with a modification, deleting into AirPortBrcmFixUp.kext the 94360 injector from Plugins folder.

And after that in Big Sur 11.6.6 is working perfectly, but I read here https://github.com/acidanthera/bugtracker/issues/1929 that there is a problem with Monterey 12.1+ related with the BCM 94360, I tried a lot of kexts and modifications, so in the previous link, I tried some debug files, and the option "brcmfx-delay=(15000 | 27000 | 30000)".  Nothing of that solves the problem.

But I read that on Monterey 12.0.1 is working the card (94360), so I create a 12.0.1 installer, and after booting up the recovery, voila, the WiFi is working fine (my 943224HMS), installation of 12.0.1 too, but I also got working WiFi in Monterey 12.3.1 but only in the recovery, not in the 12.3.1 installed, here the system crash after reading the kext, and gets into a KP, and I stuck here.

I always follow yours guides, I read that you recommend this card for our HP Ivy Bridge laptops, and so, I bought this (14e4:4353), but it works up to 12.0.1, and after putting the AirPortBrcmFixUp.kext in 12.1+ results into a KP, so I understood the problem was the same as in the 94360 (14e4:43a0). The curious case is that with 12.3.1 recovery boots without any problem and WiFi at recovery works perfectly, but in a 12.3.1 installation that is the problem.

Also I know that with 94360 (14e4:43a0) and 12.1+ there is a bug from Apple side.

PD: I´m "asdesoso" from InsanelyMac, that in the past I gave some feedback about your installers for EliteBook and ProBook.

Thank you very much.

Cheers.

**Comment by chris1111** [comment]
send me on zip file the EFI folder create from the HP Probook Elitebook program

**Comment by avidal40** [comment]
[EFI.zip](https://github.com/chris1111/HP-ProbookEliteBook-Package-Creator-Clover/files/8506347/EFI.zip)
I recreate again the complete EFI folder, and I notice that it reboots with your AirPortBrcmFixUp.kext, if I delete it, the laptop boots normally. Also I notice that your AirPortBrcmFixUp.kext is not the same as in acidanthera website, maybe here is the solution.

Cheers.

**Comment by chris1111** [comment]
try this one
[AirportBrcmFixup.kext.zip](https://github.com/chris1111/HP-ProbookEliteBook-Package-Creator-Clover/files/8506821/AirportBrcmFixup.kext.zip)

**Comment by avidal40** [comment]
It works only in 12.3.1 recovery, trying to boot installed 12.3.1 reboots again the laptop.

**Comment by avidal40** [comment]
Do you know or think where is the problem?
Thanks.

**Comment by chris1111** [comment]
I have this card whithout problem clover and OpenCore

**Comment by avidal40** [comment]
The BCM943224HMS in Monterey 12.3.1?

**Comment by chris1111** [comment]
> The BCM943224HMS in Monterey 12.3.1?

From siéra to Monterey all version

**Comment by avidal40** [comment]
But Monterey 12.0.1 or later, such as 12.3.1?

**Comment by chris1111** [comment]
> But Monterey 12.0.1 or later, such as 12.3.1?

any monterey version

**Comment by avidal40** [comment]
And what config or kext are you using?
To try me too.
Thanks.

**Comment by chris1111** [comment]
all file is in the repos, [make sur bios setitng is follow](https://github.com/chris1111/HP-ProbookEliteBook-Package-Creator-Clover#bios-setup)

**Comment by avidal40** [comment]
I have all the settings as your guide, except only one, the bios version, I have F73, instead of F61, F62 or F64.
Do you think it could the problem?
But in the past I give you some feedback about this specific thing, the bios version, I had F73 from April 2019 without any problem, and always following your guides.
Thanks.

**Comment by avidal40** [comment]
I read in the details of the post-installation program, that AirPortBrcmFixUp.kext specifies the card BCM94322HMS instead of mine BCM94322**4**HMS.
What card do you have BCM94322HMS or BCM94322**4**HMS?
Because I tried everything and it doesn´t work at installed 12.3.1.

**Comment by chris1111** [comment]
I have BCM94322HMS but now I use AzureWave WLAN+BT BCM94352HMB
- Wifi mini PCI Wifi mini PCI [AzureWave WLAN+BT BCM94352HMB](https://www.aliexpress.com/item/4000385703330.html )

You are right, I try BCM94322HMS on latest Monterey Beta then the laptop reboot

I will try to find a Fix today

I will also try [AzureWave WLAN+BT BCM94360HMB]

**Comment by avidal40** [comment]
> I have BCM94322HMS but now I use AzureWave WLAN+BT BCM94352HMB
> 
> * Wifi mini PCI Wifi mini PCI [AzureWave WLAN+BT BCM94352HMB](https://www.aliexpress.com/item/4000385703330.html)
> 
> You are right, I try BCM94322HMS on latest Monterey Beta then the laptop reboot
> 
> I will try to find a Fix today
> 
> I will also try [AzureWave WLAN+BT BCM94360HMB]

Ok, thank you very much.

**Comment by chris1111** [comment]
I am not able to find any fix, sorry.
You need to change the adapter for a BCM94352HMB-Adaptador 
I have update the link on the page

**Comment by chris1111** [comment]
Today I will try to use BCM943224HMS with a snaspshot disk
Stay tune 😆

**Comment by avidal40** [comment]
Ok, thank you, but yesterday I ordered a DW1550 with the combo BCM94352HMB/BCM20702A0.
But the hackintosh world is to try, try, try and play the game hehehe.

**Comment by chris1111** [comment]
NOT WORKING 🪓
👎🏻

**Comment by avidal40** [comment]
> Today I will try to use BCM943224HMS with a snaspshot disk Stay tune 😆

So the BCM943224HMS is out totally in Monterey (12.3.1), I think that DW1550 is the best option for me.
Thank you very much.
Cheers.

**Comment by chris1111** [comment]
Fix

[See recommand Wifi](https://github.com/chris1111/HP-ProbookEliteBook-Package-Creator-Clover#recommand-wifi)
[commits](https://github.com/chris1111/HP-ProbookEliteBook-Package-Creator-Clover/commit/f59e8d1f78220f425b9eedbf221120cd219b096b)
