### ISSUE TITLE
no dsdt in efi folder

### ISSUE THREAD

**Issue by robi62** [chris1111/HP-ProbookEliteBook-Package-Creator-Clover#3]
Hi Chris I have been trying to install both packages but result is the same for my 9470m no dsdt found in efi folder so I cannot boot into bigsur or Monterey The installation log shows no patchmatic found 
/MYPatcher: line 25: ./patchmatic: No such file or directory
/MYPatcher: line 29: ./iasl: No such file or directory
Apr 22 11:10:39 MacBook-Air package_script_service[1328]: ./postinstall: ./MYPatcher: line 36: ./iasl: No such file or directory
Apr 22 11:10:39 MacBook-Air package_script_service[1328]: ./postinstall: ./MYPatcher: line 44: ./iasl: No such file or directory

Any ideas why is doing this this is both with clover and oc...

**Comment by chris1111** [comment]
Delete EFI of previous install then Boot macOS from (Install Media HP Laptop OC.app) and this issue was gone
