### ISSUE TITLE
Does not accept files obtained with gibmacOS

### ISSUE THREAD

**Issue by noyannus** [chris1111/HP-ProbookEliteBook-Package-Creator-Clover#7]
The CC Clover throws an error, when it tries to build a USB from a macOS installer that was downloaded and build with gibmacOS. 

Tried with 
Ventura 13.0.1 (22A400)
Big Sur 11.7.1 (20G918)
Monterey 12.6.1 (21G217)

![Screenshot](https://user-images.githubusercontent.com/6339921/201475742-b56131ff-e231-4454-8396-a4068dc3da67.png)

**Comment by chris1111** [comment]
SIP is not disable I think

**Comment by noyannus** [comment]
It is:
```
~ % csrutil status
System Integrity Protection status: disabled.
```

**Comment by chris1111** [comment]
in which version of macOS are you trying this?

**Comment by noyannus** [comment]
10.15.7 (19H1615)

**Comment by chris1111** [comment]
You can not create a macOS 11, 12 , 13 on Catalina; Apple not permited this

Here no Issue on Ventura 13 with this program

![Screenshot 2022-11-12 at 9 13 10 AM](https://user-images.githubusercontent.com/6248794/201478203-377dbfe8-2c33-47ca-934e-75d6fd30ddc4.png)

**Comment by noyannus** [comment]
Ahhh! Thanks!
